### ISSUE TITLE
TypeError: Can't instantiate abstract class PQueue with abstract methods __next__

### ISSUE THREAD

**Issue by MrEliptik** [kanghyojun/mmcq.py#12]
I'm trying to use your code to replace Kmean clustering to get the dominant color of an image. With python 3.6.7, I get the following error when calling `color = get_dominant_color(filename=test_file)`.

Error:
`
Traceback (most recent call last):
  File "benchmarks.py", line 41, in <module>
    main()
  File "benchmarks.py", line 37, in main
    color = get_dominant_color(filename=test_file)
  File "/home/mreliptik/Documents/dev/AmbianceLightDisplay/mmcq/__init__.py", line 36, in get_dominant_color
    with get_palette(color_count, quality, **kwards) as palette:
  File "/home/mreliptik/.pyenv/versions/3.6.7/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/mreliptik/Documents/dev/AmbianceLightDisplay/mmcq/__init__.py", line 31, in get_palette
    c_map = mmcq(colors, color_count)
  File "/home/mreliptik/Documents/dev/AmbianceLightDisplay/mmcq/quantize.py", line 139, in mmcq
    pq = PQueue(lambda x, y: x.count >= y.count)
TypeError: Can't instantiate abstract class PQueue with abstract methods __next__
`

I'll investigate that on my side, but in the meantime, do you know why it does that?

Regards,
Victor

**Comment by kanghyojun** [comment]
Now support python3 ! https://pypi.org/project/mmcq.py/

**Comment by kanghyojun** [comment]
https://github.com/kanghyojun/mmcq.py/commit/a52a3b12a23eebc9e547a5a42e38d9063f5cfcea#diff-2b478fdb4a1438671193755d7ed5f9266a804018f41558e53bdbf9a5032563a1R54
